---
# Handlers for MariaDB

- name: restart mysql
  service: name=mysql state=restarted

- name: start mysql
  service: name=mysql state=started

- name: stop mysql
  service: name=mysql state=stopped

- name: reload ulimit
  service: name=mysql state=restarted 

