---

# maps ansible_distribution to the pgdg repository package name
postgresql_pgdg_dists:
  RedHat: redhat
  CentOS: centos
  Scientific: sl
  SLC: sl
  OracleLinux: oraclelinux

postgresql_pgdg_families:
  Fedora: fedora

postgresql_pgdg_shortfamilies:
  Fedora: fedora

# postgresql version
postgresql_default_version: 9.6

# postgresql replication client1
repl_client1: 192.168.10.67/32
# postgresql replication server1
repl_server1: 192.168.10.66/32
