---
haproxy_socket: /var/lib/haproxy/stats
haproxy_chroot: /var/lib/haproxy
haproxy_user: haproxy
haproxy_group: haproxy

# Frontend settings.
haproxy_frontend_name: 'hafrontend'
haproxy_frontend_bind_address: '*'
haproxy_frontend_port: 3306
haproxy_frontend_mode: 'tcp'

# Backend settings.
haproxy_backend_name: 'habackend'
haproxy_backend_mode: 'tcp'
haproxy_backend_balance_method: 'roundrobin'

# List of backend servers.
haproxy_backend_servers:
  - name: db01
    address: 192.168.20.101
  - name: db02
    address: 192.168.20.102

# Extra global vars (see README for example usage).
haproxy_global_vars: []
