---

# Servers of PGSQL Masters
- hosts: PGServersMaster 
  become: yes
  roles:
          #    - { role: CentOS_Srv }
          - { role: PGServersMaster,postgresql_default_version: 10 }

# Servers of PGSQL Slaves
- hosts: PGServersSlave
  become: yes
  roles:
          #    - { role: CentOS_Srv }
          - { role: PGServersMaster,postgresql_default_version: 10 }
          - { role: PGServersSlave,postgresql_default_version: 10 }
