---
- hosts: IntranetMonitoring WebServers WebMonitoring
  become: yes
  roles:
    - { role: CentOS_Srv }

- hosts: WebServers
  become: yes
  roles:
    - { role: nginx }
    - { role: journaldClient }
    - { role: rsyslogClient }

- hosts: IntranetMonitoring
  become: yes
  roles:
    - { role: ntpd }
    - { role: journaldSrv }
    - { role: rsyslogSrv }

- hosts: WebMonitoring 
  become: yes
  roles:
    - { role: nginx }
    - { role: journaldClient }
    - { role: rsyslogClient }

