---
- hosts: WebServers logsrv 
  become: yes
  roles:
    - { role: CentOS_Srv }

- hosts: web01
  become: yes
  roles:
    - { role: nginx }
    - { role: journaldClient }

- hosts: logsrv
  become: yes
  roles:
    - { role: ntpd }
    - { role: journaldSrv }
