---
- hosts: WebServers logsrv 
  become: yes
  roles:
    - { role: CentOS_Srv }

- hosts: web01
  become: yes
  tasks:

  roles:
    - { role: nginx }

- hosts: logsrv
  become: yes
  tasks:

  roles:
    - { role: ntpd }

